ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS open NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS high NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS low NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS volume NUMERIC;

ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS bb_mavg_20 NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS bb_hband_20 NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS bb_lband_20 NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS bb_width_20 NUMERIC;
ALTER TABLE stock_features ADD COLUMN IF NOT EXISTS bb_pband_20 NUMERIC;

ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS open_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS high_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS low_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS volume_z NUMERIC;

ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS bb_mavg_20_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS bb_hband_20_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS bb_lband_20_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS bb_width_20_z NUMERIC;
ALTER TABLE stock_features_zscore ADD COLUMN IF NOT EXISTS bb_pband_20_z NUMERIC;
