-- Add multi-horizon sentiment features to gold table.

ALTER TABLE daily_symbol_sentiment
    ADD COLUMN IF NOT EXISTS sentiment_1h DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sentiment_24h DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sentiment_3d DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS news_volume INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sentiment_volatility DOUBLE PRECISION NOT NULL DEFAULT 0;
