FEATURE_COLUMNS = [
    "return_1d",
    "return_5d",
    "return_10d",
    "return_20d",
    "sma_5",
    "sma_10",
    "sma_20",
    "sma_50",
    "sma_100",
    "ema_10",
    "ema_20",
    "ema_50",
    "ema_100",
    "volatility_5",
    "volatility_10",
    "volatility_20",
    "volatility_50",
    "volatility_100",
    "lag_1",
    "lag_2",
]

FEATURE_COLUMNS_Z = [
    "return_1d_z",
    "return_5d_z",
    "return_10d_z",
    "return_20d_z",
    "sma_5_z",
    "sma_10_z",
    "sma_20_z",
    "sma_50_z",
    "sma_100_z",
    "ema_10_z",
    "ema_20_z",
    "ema_50_z",
    "ema_100_z",
    "volatility_5_z",
    "volatility_10_z",
    "volatility_20_z",
    "volatility_50_z",
    "volatility_100_z",
    "lag_1_z",
    "lag_2_z",
]

TARGET_COLUMN = "target_return_5d"
